name: Docker Image CI for PHP 8.3

on:
#  schedule:
#    - cron: "00 3 * * 0"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push light
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags: sigblue/apache-php:84-light
       build-args: VERSION=8.4-rc-apache-bookworm
       target: light
    - name: Build and push standard
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags: sigblue/apache-php:84-standard
       build-args: VERSION=8.4-rc-apache-bookworm
       target: standard
    - name: Build and push full
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags: sigblue/apache-php:84-full
       build-args: VERSION=8.4-rc-apache-bookworm
       target: full

