name: Docker Image CI for PHP 8.1

on:
  schedule:
    - cron: "00 16 * * 1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push light
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags: sigblue/apache-php:81-light
       build-args: VERSION=8.1
       target: light
    - name: Build and push standard
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags: sigblue/apache-php:81-standard
       build-args: VERSION=8.1
       target: standard
    - name: Build and push full
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags: sigblue/apache-php:81-full
       build-args: VERSION=8.1
       target: full
